news/main/urls.py
from django.urls import path
from .import views

app_name = 'main'

urlpatterns = [
	path('',views.HomePageView.as_view(), name='home'),
	path('post-detail/<slug:post_slug>',views.postDetailPage, name='post_detail'),
    path('category/detail/<slug>',views.CategoryDetailView.as_view(),name='category_detail'),
    path('post/<slug:tag_slug>',views.tagDetailPage, name='tag_detail'),
]

news/news/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

news/main/models.py
from django.db import models
from django.urls import reverse
# ForeignKey = birga kop ulash
# OneToOneField = birga bir ulash
# ManyToManyField = Kopga kopga ulash

class Category(models.Model):
	name = models.CharField('Nomi:', max_length=100)
	slug = models.SlugField('*', max_length=100, unique=True)

	def __str__(self):
		return f"{self.name}"

		def get_absolute_url(self):
			return reverse('main:category_detail', kwargs={'category_slug':self.slug})

	class Meta:
		verbose_name = 'Kategoriya'
		verbose_name_plural = 'Kategoriyalar'

class Tags(models.Model):
	name = models.CharField('Nomi:', max_length=100)
	slug = models.SlugField('*', max_length=100, unique=True)

	def __str__(self):
		return f"{self.name}"

	def get_absolute_url(self):
		return reverse('main:tag_detail', kwargs={'tag_slug':self.slug})

	class Meta:
		verbose_name = 'Teg'
		verbose_name_plural = 'Teglar'


class Post(models.Model):
	title = models.CharField('Nomi', max_length=300)
	slug = models.SlugField('*', max_length=100, unique=True)
	author = models.CharField('Aftor', max_length=80)
	image = models.ImageField('Rasmi', upload_to='posters/')
	body = models.TextField('Body')
	views = models.PositiveIntegerField('Korildi', default=0)
	published = models.DateTimeField(auto_now_add=True)
	category = models.ForeignKey(Category,on_delete=models.CASCADE,related_name='posts')
	tag = models.ManyToManyField(Tags,related_name='products')

	def __str__(self):
		return f"{self.title}"

	def get_absolute_url(self):
		return reverse('main:post_detail', kwargs={'post_slug':self.slug})

	class Meta:
		verbose_name = 'Maqola'
		verbose_name_plural = 'Maqolalar'


class Comment(models.Model):
	post = models.ForeignKey(Post,
	on_delete=models.CASCADE,
	related_name='comments')
	date = models.DateTimeField('Bildirilgan sana',
		auto_now_add=True,
		null=True)
	name = models.CharField('Ismingiz', max_length=50)
	email = models.EmailField('Email')
	subject = models.CharField('Mavzu', max_length=150)
	comment = models.TextField('Xabar matni')

	def __str__(self):
		return f"{self.name}"

	class Meta:
		verbose_name = 'Muhokama'
		verbose_name_plural = 'Muhokamalar'

news/main/forms.py
from django import forms
from .models import Comment

class AddCommentForm(forms.ModelForm):
	# Add Comment 
	
	class Meta:
		model = Comment
		fields = '__all__' # Hamma maydonini olish
		exclude = ['post','subject'] # qaysi maydonlarni korsatmaslik
		# fields = ['name', 'email','subject', 'comment'] 
		widgets = {
		'comment': forms.TextInput(attrs={'class': 'form-control'}), # or whatever class you want to apply
		# and so on
		}

news/main/views.py
from django.shortcuts import render,get_object_or_404
from django.views.generic import TemplateView,ListView,DetailView
from .models import *	
from .forms import AddCommentForm
# Create your views here.

class HomePageView(ListView):
	model = Post
	paginate_by = 6
	template_name = 'index.html'
	context_object_name = 'posts'


def tagDetailPage(request, tag_slug):
	tag = get_object_or_404(Tags, slug=tag_slug)
	print(tag)
	post = Post.objects.filter(tag=tag)
	return  render(request, 'tag.html', {'posts':post})


class CategoryDetailView(DetailView):
	model = Category
	slug_field = 'slug'
	template_name = 'category.html'


def postDetailPage(request, post_slug):
	post = Post.objects.get(slug=post_slug)
	if request.method == 'POST':
		form = AddCommentForm(request.POST)
		if form.is_valid():
			f = form.save(commit=False)
			f.post = post
			f.save()
	else:
		form = AddCommentForm()
	post.views += 1
	post.save()
	context = {
		'post':post,
		'form':form,
	}
	return render(request, 'single.html', context)

def entry_not_found(request, exception=None):
    return render(request, '404.html')

news/templates/category.html
{% extends "wrapper.html" %}
{% block content %}
 
<main>

    <div class="row">
      <div class="col s10 m10">
        <div style="margin-left:20px;margin-bottom: -20px;border-bottom: 1px solid black;">
        <h4><b>{{object.name}}</b></h4>
    </div>
      </div>
    </div>

<div class="container">
  <div class="row">
    {% for item in object.posts.all %}   
    <div class="col xl4 l4 m4 s12">
      <div class="card medium">
        <div class="card-image">
          <a href="{{item.get_absolute_url}}">
            <img src="{{item.image.url}}">
          <span class="card-title">{{item.title}}</span>
          </a>
        </div>
        <div class="card-content">
          <p>{{item.body|truncatewords:20}}</p>
        </div>
        <div class="card-action">
          <a href="{{item.get_absolute_url}}"><i class="fas fa-user">{{item.author}}</i></a>
          <a href="{{item.get_absolute_url}}"><i class="fas fa-clock">{{item.published}}</i></a>
          <a href="{{item.get_absolute_url}}"><i class="fas fa-eye">{{item.views}}</i></a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

</main>

{% endblock  %}

news/templates/index.html
{% extends "wrapper.html" %}
{% load static %}
{% block content %}
<main>
<!-- Slider news -->
<div class="container">
  <br><br><br>
  <div class="col xl12 l12 m12 s12">
    <div class="slider">
    <ul class="slides">
      {% for item in home %}
      <li>
        <a href="{{item.get_absolute_url}}">
        <img src="{{item.image.url}}">
        </a> <!-- random image -->
        <div class="caption center-align">
          <h3>{{item.title}}</h3>
        </div>
      </li>
      {% endfor %}
    </ul>
  </div>
  </div>
</div>
<!-- Ending of slider of news -->


<!-- Latest news -->
<div class="row">  
  <div class="col s12 m12">
    <div style="margin-left:20px;margin-bottom: -20px;border-bottom: 1px solid black;">
        <h4><b>So'ngi Yangiliklar</b></h4>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    {% for post in posts %}   
    <div class="col xl4 l4 m4 s12">
      <div class="card large">
        <div class="card-image">
          <a href="{{post.get_absolute_url}}">
            <img src="{{post.image.url}}">
          </a>
        </div>
        <div class="card-content">
          <span style="color:blue;"><a href="{{top.get_absolute_url}}"><b>{{post.title|upper|truncatewords:5}}</b></a></span>
          <p>{{post.body|truncatewords:20}}</p>
        </div>
        <div class="card-action">
          <a href="{{post.get_absolute_url}}"><i class="fas fa-user">{{post.author}}</i></a>
          <a href="{{post.get_absolute_url}}"><i class="fas fa-clock">{{post.published}}</i></a>
          <a href="{{post.get_absolute_url}}"><i class="fas fa-eye">{{post.views}}</i></a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
<!-- Ending of Latest news -->

<!-- Top news -->
<div class="row">  
  <div class="col s12 m12">
    <div style="margin-left:20px;margin-bottom: -20px;border-bottom: 1px solid black;">
        <h4><b>Top Yangiliklar</b></h4>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    {% for top in tops %}
    <div class="col xl4 l4 m4 s12">
      <div class="card large">
        <div class="card-image">
          <a href="{{top.get_absolute_url}}">
          <img src="{{top.image.url}}">
        </a>
      </div>
      <div class="card-content">
          <span style="color:blue;"><a href="{{top.get_absolute_url}}"><b>{{top.title|upper|truncatewords:5}}</b></a></span>
          
          <p>{{top.body|truncatewords:20}}</p>
        </div>
        <div class="card-action">
          <a href="#"><i class="fas fa-user">{{top.author}}</i></a>
          <a href="#"><i class="fas fa-clock">{{top.published}}</i></a>
          <a href="#"><i class="fas fa-eye">{{top.views}}</i></a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
<!-- Ending of Top news -->

<!-- Other news -->
<div class="row">  
  <div class="col s12 m12">
    <div style="margin-left:20px;margin-bottom: -20px;border-bottom: 1px solid black;">
        <h4><b>Boshqa Yangiliklar</b></h4>
    </div>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col xl6 l6 m6 s12">
      <div class="row">
      {% for item in home %} 
      <div class="card">
        <div class="card-image">
          <a href="{{item.get_absolute_url}}">
          <img src="{{item.image.url}}">
          </a>
        </div>
        <div class="card-content">
          <span style="color:blue;"><a href="{{top.get_absolute_url}}"><b>{{item.title|upper}}</b></a></span>
          <p>{{item.body|truncatewords:20}}</p>
        </div>
        <div class="card-action">
          <a href="#"><i class="fas fa-user">{{item.author}}</i></a>
          <a href="#"><i class="fas fa-clock">{{item.published}}</i></a>
          <a href="#"><i class="fas fa-eye">{{item.views}}</i></a>
        </div>
      </div>
     {% endfor %}
      </div>
    </div>
<div class="col xl6 l6 m6 s12">
  <div class="row">
  <div class="card-panel z-depth-3" id="categoryTag">
    <div class="header">
      <h4><b>Kategoriyalar</b></h4>
    </div>
<!-- Category -->
  <div class="collection">
    {% for category in categories %}
    <a href="{% url 'main:category_detail' category.slug %}" class="collection-item"><b>{{category.name}}</b></a>
    {% endfor %}
  </div>
  </div>
<!-- Ending of Category -->

<!-- Tags -->
  <div class="card-panel z-depth-3" id="categoryTag">
    <div class="header">
      <h4><b>Teglar</b></h4>
    </div>
  <div class="row">  
    {% for tag in tags %}
      <a href="{{tag.get_absolute_url}}" class="btn">{{tag.name}}</a>
    {% endfor %}
  </div>
  </div>
<!-- Ending of Tags -->
  

  <h4 class="center"><b>Andijon:</b></h4>
  <a href="https://clck.yandex.ru/redir/dtype=stred/pid=7/cid=1228/*https://yandex.uz/pogoda/10335" target="_blank"><img src="https://info.weather.yandex.net/10335/2_white.ru.png?domain=uz" border="0" alt="Яндекс.Погода"/><img width="5" height="5" src="https://clck.yandex.ru/click/dtype=stred/pid=7/cid=1227/*https://img.yandex.ru/i/pix.gif" alt="" border="0"/></a>
</div>
<!-- Ending of Other news -->

<!-- All News -->
<br><br><br><br><br><br><br>
<div class="card-panel z-depth-3" id="categoryTag">
  <div class="header"><h4><b>Boshqa maqolalar</b></h4></div>
  <div class="row">
    <ul class="collection">
      {% for posts in all_post %}
      <li class="collection-item"><h6><b><a href="{{posts.get_absolute_url}}">{{posts.body|truncatewords:10}}</a></b></h6></li>
      {% endfor %}
    </ul>
  </div>
</div>
<!-- Ending of All News -->

</div>
</div>

</main>

{% endblock %}

  </body>
</html>

news/templates/single.html
{% extends "wrapper.html" %}
{% load static %}
{% load crispy_forms_tags %}
<script>
  if ( window.history.replaceState ) {
  window.history.replaceState( null, null, window.location.href );
  }
  </script>
{% block content %}

<main>

<div class="container">
   <br><br><br>
   <!-- Single Photo -->
  <div class="row">
    <div class="col xl8 l8 m8 s12">
      <div class="row">
      <div class="card z-depth-3">
        <div class="card-image">
          <img src="{{post.image.url}}" alt="">
          
        </div>
        <div class="card-content">
          <span style="color:blue;"><a href="{{top.get_absolute_url}}"><b>{{post.title|upper}}</b></a></span>
          <h6><b>{{post.body}}</b></h6>
        </div>
        <div class="card-action">
          <a href="{{post.get_absolute_url}}"><i class="fas fa-user">{{post.author}}</i></a>
          <a href="{{post.get_absolute_url}}"><i class="fas fa-clock">{{post.published}}</i></a>
          <a href="{{post.get_absolute_url}}"><i class="fas fa-eye">{{post.views}}</i></a>
        </div>
      </div>

<div class="col xl12 l12 m12 s12">
  <div class="row">
  <div class="card-panel z-depth-3">
    <div class="header">
      <h4><b>Izohlar ({{post.comments.all.count}})</b></h4>
      <ul class="collection">
  {% for commentator in post.comments.all %}
    <li class="collection-item avatar">
      <img src="/static/img/john.png" alt="" class="circle">
      <h4 class="title">{{commentator.name}}<span class="right">{{commentator.date}}</span></h4>
      <p>
        {{commentator.comment}}
      </p>
    </li>
  {% endfor %}
  </ul>
    </div>
  </div>
  </div>
</div>


      </div>
    </div>
  <!-- Ending of Single Photo -->

  <!-- CategoyTag -->

  <div class="col xl4 l4 m4 s12">
    <div class="row">
      <div class="card-panel z-depth-" id="categoryTag">
        <div class="header">
          <h4><b>Kategoriyalar</b></h4>
        </div>
        <!-- Category -->
        <div class="collection">
          {% for category in categories %}
          <a href="{% url 'main:category_detail' category.slug %}" class="collection-item"><b>{{category.name}}</b></a>
          {% endfor %}
        </div>
        <!-- Ending of Category -->
      </div>

      <!-- Tags -->
        <div class="card-panel z-depth-3" id="categoryTag">
    <div class="header">
      <h4><b>Teglar</b></h4>
    </div>
  <div class="row">  
    {% for tag in tags %}
      <a href="{{tag.get_absolute_url}}" class="btn">{{tag.name}}</a>
    {% endfor %}
  </div>
  </div>
      <!-- Ending of Tags -->
  <h4 class="center"><b>Andijon:</b></h4>
  <a href="https://clck.yandex.ru/redir/dtype=stred/pid=7/cid=1228/*https://yandex.uz/pogoda/10335" target="_blank"><img src="https://info.weather.yandex.net/10335/2_white.ru.png?domain=uz" border="0" alt="Яндекс.Погода"/><img width="5" height="5" src="https://clck.yandex.ru/click/dtype=stred/pid=7/cid=1227/*https://img.yandex.ru/i/pix.gif" alt="" border="0"/></a>
   



  <!-- Ending of CategoyTag -->
<!-- All News -->
<div class="card-panel z-depth-3" id="categoryTag">
  <div class="header"><h4><b>Boshqa maqolalar</b></h4></div>
  <div class="row">
    <ul class="collection">
      {% for posts in all_post %}
      <li class="collection-item"><h6><b><a href="{{posts.get_absolute_url}}">{{posts.body|truncatewords:20}}</a></b></h6></li>
      {% endfor %}
    </ul>
    </ul>
      </div>
    </div>
  </div>
</div>
</div>
</div>

<!-- Ending of All News -->


<!-- Comment Form -->
<div class="container">
<div class="col xl8 l8 m8 s12">
  <div class="row">
    <div class="card-panel z-depth-3">
      <div class="header">
        <h4><b>Izoh qoldirish</b></h4>
      </div>
        <form action="" id="form" method="POST">
          {% csrf_token %}
          {{form|crispy}}
          <center>
          <input class="btn" type="submit" value="Izoh qoldirish">
          </center>
        </form>
    </div>
  </div>
</div>
</div>


<!-- Ending of Comment Form -->


</main>


  {% endblock  %}

  </body>
</html>

news/templates/tag.html
{% extends "wrapper.html" %}
{% block content %}
 
<main>

    <div class="row">
      <div class="col s10 m10">
        <div style="margin-left:20px;margin-bottom: -20px;border-bottom: 1px solid black;">
        <h4><b>{{posts.tag.name}}</b></h4>
    </div>
      </div>
    </div>

<div class="container">
  <div class="row">
    {% for item in posts %}   
    <div class="col xl4 l4 m4 s12">
      <div class="card">
        <div class="card-image">
          <a href="{{item.get_absolute_url}}">
            <img src="{{item.image.url}}">
          <span class="card-title">{{item.title}}</span>
          </a>
        </div>
        <div class="card-content">
          <p>{{item.body|truncatewords:20}}</p>
        </div>
        <div class="card-action">
          <a href="{{item.get_absolute_url}}"><i class="fas fa-user">{{item.author}}</i></a>
          <a href="{{item.get_absolute_url}}"><i class="fas fa-clock">{{item.published}}</i></a>
          <a href="{{item.get_absolute_url}}"><i class="fas fa-eye">{{item.views}}</i></a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

</main>

{% endblock  %}

news/templates/wrapper.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0"/>
  <title>Yangiliklar!</title>

  <!-- CSS  -->
  <link rel="short icon" href="https://icons.iconarchive.com/icons/pelfusion/folded-flat/128/News-icon.png">
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous" />
  <link href="/static/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>
  <link href="/static/css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>
 
</head>
<body>
  <nav class="light-blue lighten-1" role="navigation">
    <div class="nav-wrapper container"><a id="logo-container" href="{% url 'main:home' %}" class="brand-logo">AsralkhanovBlog</a>
      <ul class="right hide-on-med-and-down">
        <li><a href="{% url 'main:home' %}">Bosh sahifa</a></li>
      </ul>

      <ul id="nav-mobile" class="sidenav">
        <li><a href="{% url 'main:home' %}">Bosh sahifa</a></li>
      </ul>
      <a href="#" data-target="nav-mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
    </div>
  </nav>

<script>
  if ( window.history.replaceState ) {
  window.history.replaceState( null, null, window.location.href );
  }
  </script>
  {% block content %}
  


  {% endblock  %}



  
  <footer class="page-footer light-blue lighten-1">
    <div class="container">
      <div class="row">
        <div class="col l6 s12">
          <h3 class="white-text">AsralkhanovBlog</h3>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text"><b>Teglar</b></h5>
          <ul>
            {% for tag in footer_tags %}
            <li><a class="white-text" href="{{tag.get_absolute_url}}"><b>{{tag.name}}</b></a></li>
            {% endfor %}
          </ul>
        </div>
        <div class="col l3 s12">
          <h5 class="white-text"><b>Kategoriyalar</b></h5>
          <ul>
            {% for category in footer_category %}
            <li><a class="white-text" href="{% url 'main:category_detail' category.slug %}"><b>{{category.name}}</b></a></li>
            {% endfor %}
          </ul>
        </div>
      </div>
    </div>
    <div class="footer-copyright">
      <div class="container center">
      Made by <a class="orange-text text-lighten-3" href="http://materializecss.com">Asralkhanov</a>
      </div>
    </div>
  </footer>


  <!--  Scripts-->
  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
  <script src="/static/js/materialize.js"></script>
  <script src="/static/js/init.js"></script>